### ISSUE TITLE
类型“dotnetCampus.Cli.Core.SingleOptimizedList”的对象无法转换为类型“System.String”。

### ISSUE THREAD

**Issue by walterlv** [dotnet-campus/dotnetCampus.CommandLine#2]
当属性声明为字符串，但实际上参数传入了多个值时，将抛出类型转换错误。期望是一个专属可以定位的错误。

```
System.ArgumentException:“类型“dotnetCampus.Cli.Core.SingleOptimizedList”的对象无法转换为类型“System.String”。”

   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at dotnetCampus.Cli.Parsers.RuntimeOptionParser`1.SetValue(Char shortName, IReadOnlyList`1 values) in C:\Users\lvyi\.nuget\packages\dotnetcampus.commandline.source\1.0.0\src\Parsers\RuntimeOptionParser.cs:line 69
   at dotnetCampus.Cli.CommandLine.As[T](ICommandLineOptionParser`1 parser) in C:\Users\lvyi\.nuget\packages\dotnetcampus.commandline.source\1.0.0\src\CommandLine.cs:line 101
   at dotnetCampus.Cli.Utils.CommandLineHelpers.MatchAndHandle[TVerb](CommandLine commandLine, String possibleVerb, Func`2 handler, ICommandLineOptionParser`1 parser) in C:\Users\lvyi\.nuget\packages\dotnetcampus.commandline.source\1.0.0\src\Utils\CommandLineHelpers.cs:line 133
   at dotnetCampus.Cli.CommandLineAsyncHandlerBuilder.<>c__DisplayClass6_0`1.<AddHandler>b__0(String verb) in C:\Users\lvyi\.nuget\packages\dotnetcampus.commandline.source\1.0.0\src\CommandLineHandlerBuilder.cs:line 189
   at dotnetCampus.Cli.StateMachine.HandleVerbStateMachine`1.<Run>d__3.MoveNext() in C:\Users\lvyi\.nuget\packages\dotnetcampus.commandline.source\1.0.0\src\StateMachine\HandleVerbStateMachine.cs:line 63
   at dotnetCampus.Cli.CommandLineAsyncHandlerBuilder.RunAsync() in C:\Users\lvyi\.nuget\packages\dotnetcampus.commandline.source\1.0.0\src\CommandLineHandlerBuilder.cs:line 221
```

**Comment by walterlv** [comment]
Fixed by #10
